version: '3.9'

services:
  # MongoDB service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db

  # Node API service
  api:
    image: nodeapp
    ports:
      - "3030:3030"
    depends_on: 
      - mongo_db

  # Mongo Express service
  mongo_express:
    image: mongo-express:latest
    container_name: mongo_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ""
      ME_CONFIG_MONGODB_ADMINPASSWORD: ""
      ME_CONFIG_MONGODB_SERVER: mongo_db
    depends_on:
      - mongo_db

volumes:
  mongo_data: {}
